version: '3.7'
services:

  rabbitmq:
    image: rabbitmq:3.5.3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - twilio-network
  
  zipkin-server:
  #[INFO] Successfully built image 'docker.io/sv/twilioprj-anaming-server:0.0.1-SNAPSHOT'
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"
    restart: always
    networks:
      - twilio-network
  naming-server:
  #[INFO] Successfully built image 'docker.io/sv/twilioprj-anaming-server:0.0.1-SNAPSHOT'
    image: sv/twilioprj-anaming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    restart: always
    networks:
      - twilio-network
      
  bapi-gateway:
  #[INFO] Successfully built image 'docker.io/sv/twilioprj-bapi-gateway:0.0.1-SNAPSHOT'
    image: sv/twilioprj-bapi-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    restart: always
    networks:
      - twilio-network
    depends_on:
      - naming-server
    environment:
      - EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE:http://naming-server:8761/eureka
      
  ctwilioui:
  #[INFO] Successfully built image 'docker.io/sv/twilioprj-ctwilioui:0.0.1-SNAPSHOT'
    image: sv/twilioprj-ctwilioui:0.0.1-SNAPSHOT
    ports:
      - "8100:8100"
    restart: always
    networks:
      - twilio-network
    depends_on:
      - naming-server
    environment:
      - EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE:http://naming-server:8761/eureka
  
  dtwiliobackend:
  #[INFO] Successfully built image 'docker.io/sv/twilioprj-dtwiliobackend:0.0.1-SNAPSHOT'
    image: sv/twilioprj-dtwiliobackend:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    restart: always
    networks:
      - twilio-network
    depends_on:
      - naming-server
    environment:
      - EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE:http://naming-server:8761/eureka
  
  eauthentication:
  #[INFO] Successfully built image 'docker.io/sv/twilioprj-eauthentication:0.0.1-SNAPSHOT'
    image: sv/twilioprj-eauthentication:0.0.1-SNAPSHOT
    ports:
      - "8200:8200"
    restart: always
    networks:
      - twilio-network
    depends_on:
      - naming-server
    environment:
      - EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE:http://naming-server:8761/eureka

networks:
  twilio-network: