
spring:
  main:
    allow-circular-references: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jpa:
    database: mysql
    show-sql: true 
    generate-ddl: false
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        type: trace   
        
##################################################################
# MULTITENANCY MASTER DATABASE SETUP
##################################################################        
multitenancy: 
  mtapp: 
    master: 
      datasource:
        url: jdbc:mysql://192.168.1.100:3306/tw_aa_masterofmasters
        username: sagar
        password: sagar
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTimeout: 20000
        maxPoolSize: 10
        idleTimeout: 300000
        minIdle: 10
        poolName: masterdb-connection-pool

##################################################################
# LOGGING LEVELS
##################################################################        
logging:
  level:
    org:
      hibernate: 
        type:  
          descriptor: 
            sql: 
              BasicBinder: TRACE 
